# Generated by Django 6.0.2 on 2026-02-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AlterField(
            model_name='customer',
            name='current_step',
            field=models.CharField(choices=[('START', 'Start'), ('LANGUAGE_SELECTED', 'Language Selected'), ('PRODUCT_SELECTED', 'Product Selected'), ('WATCHING_DEMO', 'Watching Demo'), ('VIEWING_DETAILS', 'Viewing Details'), ('PAYMENT_SELECTION', 'Payment Selection'), ('PAYMENT_PENDING', 'Payment Pending'), ('ORDER_CONFIRMED', 'Order Confirmed')], default='START', max_length=50),
        ),
    ]
